name: Continous Integration

on:
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  build:
    uses: ./.github/workflows/build.yml

